// Roman numerals read aloud (src/lib/guide/speakable.ts). Run: npm run test:speech
import { test } from "node:test";
import assert from "node:assert/strict";
import { forSpeech } from "../../src/lib/guide/speakable.ts";

type Case = [input: string, spoken: string];
const same = (inputs: string[]): Case[] => inputs.map((s) => [s, s]);

const cases: Record<string, Case[]> = {
  // ---------------------------------------------------------------- English
  "en keyword": [
    ["The tumour is grade IV.", "The tumour is grade 4."],
    ["Grade I tumours grow slowly.", "Grade 1 tumours grow slowly."],
    ["It was a grade II sprain.", "It was a grade 2 sprain."],
    ["Stage IIIB lung cancer", "Stage 3B lung cancer"],
    ["stage IV cancer", "stage 4 cancer"],
    ["Stage IA disease", "Stage 1A disease"],
    ["Stage IVC", "Stage 4C"],
    ["Type II diabetes", "Type 2 diabetes"],
    ["type I diabetes", "type 1 diabetes"],
    ["Type Ia supernovae are standard candles.", "Type 1a supernovae are standard candles."],
    ["type IIx fibres", "type 2x fibres"],
    ["Class I antiarrhythmics block sodium channels.", "Class 1 antiarrhythmics block sodium channels."],
    ["MHC class II molecules", "MHC class 2 molecules"],
    ["Class III obesity", "Class 3 obesity"],
    ["Phase I trials test safety.", "Phase 1 trials test safety."],
    ["a phase III trial", "a phase 3 trial"],
    ["Level IV evidence", "Level 4 evidence"],
    ["Tier II capital", "Tier 2 capital"],
    ["Category V hurricane", "Category 5 hurricane"],
    ["Chapter XI covers bankruptcy.", "Chapter 11 covers bankruptcy."],
    ["Read chapter IV tonight.", "Read chapter 4 tonight."],
    ["Part II of the course", "Part 2 of the course"],
    ["Part I covers cells.", "Part 1 covers cells."],
    ["Volume III", "Volume 3"],
    ["See vol. II for details.", "See vol. 2 for details."],
    ["Book I of the Iliad", "Book 1 of the Iliad"],
    ["Act I, Scene II", "Act 1, Scene 2"],
    ["In Act III the king dies.", "In Act 3 the king dies."],
    ["Article V of the treaty", "Article 5 of the treaty"],
    ["Section IX", "Section 9"],
    ["Appendix II", "Appendix 2"],
    ["Annex VII", "Annex 7"],
    ["Schedule III drugs", "Schedule 3 drugs"],
    ["Clause IV", "Clause 4"],
    ["Round II", "Round 2"],
    ["Unit VI", "Unit 6"],
    ["Lesson XII", "Lesson 12"],
    ["Module III", "Module 3"],
    ["Psalm XXIII", "Psalm 23"],
    ["Canto XXXIV", "Canto 34"],
    ["Series II", "Series 2"],
    ["Generation III reactors", "Generation 3 reactors"],
    ["Form VI students", "Form 6 students"],
    ["World War I began in 1914.", "World War 1 began in 1914."],
    ["after World War II", "after World War 2"],
    ["World Wars I and II", "World Wars 1 and 2"],
    ["Figure IV shows the cycle.", "Figure 4 shows the cycle."],
    ["fig. III", "fig. 3"],
    ["Table II lists the results.", "Table 2 lists the results."],
    ["Plate XII", "Plate 12"],
    ["Step III", "Step 3"],
    ["the Mark II tank", "the Mark 2 tank"],
    ["Division II", "Division 2"],
    ["Title IX banned discrimination.", "Title 9 banned discrimination."],
    ["Vatican II changed the Mass.", "Vatican 2 changed the Mass."],
    ["Amendment XIV", "Amendment 14"],
    ["Protocol II", "Protocol 2"],
    ["factor VIII deficiency", "factor 8 deficiency"],
    ["factor V Leiden", "factor 5 Leiden"],
    ["factor Xa inhibitors", "factor 10a inhibitors"],
    ["Complex IV of the electron transport chain", "Complex 4 of the electron transport chain"],
    ["Photosystem II splits water.", "Photosystem 2 splits water."],
    ["cranial nerve VII", "cranial nerve 7"],
    ["CN III palsy", "CN 3 palsy"],
    ["Symphony No. IX", "Symphony No. 9"],
    ["No. IV", "No. 4"],
    ["page xiv", "page 14"],
    ["pp. iii", "pp. 3"],
    ["section iii", "section 3"],
    ["Episode IV", "Episode 4"],
    ["Sonnet XVIII", "Sonnet 18"],
    ["Dynasty XVIII", "Dynasty 18"],
    ["Pillar II", "Pillar 2"],
    ["Mk II", "Mk 2"],
    ["Type-II collagen", "Type-2 collagen"],
    ["Stage IV's prognosis is poor.", "Stage 4's prognosis is poor."],
    ["type I (juvenile) diabetes", "type 1 (juvenile) diabetes"],
    ["Is it type I?", "Is it type 1?"],
    ["Stage I disease is curable.", "Stage 1 disease is curable."],
    ["Chapter XL", "Chapter 40"],
  ],
  "en lists after a keyword": [
    ["Types I, II and III", "Types 1, 2 and 3"],
    ["stages III–IV", "stages 3–4"],
    ["grade I-II", "grade 1-2"],
    ["Stage III/IV disease", "Stage 3/4 disease"],
    ["classes I to IV", "classes 1 to 4"],
    ["leads II, III and aVF", "leads 2, 3 and aVF"],
    ["Types I and II", "Types 1 and 2"],
    ["type I or type II", "type 1 or type 2"],
  ],
  "en rulers": [
    ["Henry VIII had six wives.", "Henry the Eighth had six wives."],
    ["Elizabeth II was crowned in 1953.", "Elizabeth the Second was crowned in 1953."],
    ["Elizabeth I was the last Tudor.", "Elizabeth the First was the last Tudor."],
    ["Louis XIV built Versailles.", "Louis the Fourteenth built Versailles."],
    ["King George III", "King George the Third"],
    ["Charles I was executed.", "Charles the First was executed."],
    ["Charles V ruled Spain.", "Charles the Fifth ruled Spain."],
    ["Pope John Paul II", "Pope John Paul the Second"],
    ["Pope Benedict XVI", "Pope Benedict the Sixteenth"],
    ["Pope Pius X", "Pope Pius the Tenth"],
    ["Pope John XXIII", "Pope John the Twenty-third"],
    ["Ramesses II", "Ramesses the Second"],
    ["Thutmose III", "Thutmose the Third"],
    ["Cleopatra VII", "Cleopatra the Seventh"],
    ["Ptolemy I", "Ptolemy the First"],
    ["Henry VIII's wives", "Henry the Eighth's wives"],
    ["Napoleon III", "Napoleon the Third"],
    ["Tsar Nicholas II", "Tsar Nicholas the Second"],
    ["Kaiser Wilhelm II", "Kaiser Wilhelm the Second"],
    ["Peter I founded St Petersburg.", "Peter the First founded St Petersburg."],
    ["Catherine II", "Catherine the Second"],
    ["Mehmed II took Constantinople.", "Mehmed the Second took Constantinople."],
    ["Suleiman I", "Suleiman the First"],
    ["Darius I", "Darius the First"],
    ["Louis XVIII", "Louis the Eighteenth"],
    ["Henry V", "Henry the Fifth"],
    ["Richard III", "Richard the Third"],
    ["Victor Emmanuel II", "Victor Emmanuel the Second"],
    ["Kamehameha I united Hawaii.", "Kamehameha the First united Hawaii."],
    ["Rama V modernised Siam.", "Rama the Fifth modernised Siam."],
    ["Juan Carlos I abdicated.", "Juan Carlos the First abdicated."],
    ["Leo X", "Leo the Tenth"],
    ["James I of England", "James the First of England"],
  ],
  "en other names": [
    ["Apollo XIII launched in 1970.", "Apollo 13 launched in 1970."],
    ["We watched Rocky IV.", "We watched Rocky 4."],
    ["Final Fantasy VII", "Final Fantasy 7"],
    ["Super Bowl LVII", "Super Bowl 57"],
    ["Star Wars Episode IV", "Star Wars Episode 4"],
    ["Apollo XI landed", "Apollo 11 landed"],
    ["Star Trek II", "Star Trek 2"],
  ],
  "en centuries": [
    ["the XIX century", "the 19th century"],
    ["the XXI century", "the 21st century"],
    ["the XIXth century", "the 19th century"],
    ["the XV and XVI centuries", "the 15th and 16th centuries"],
    ["the XVIII dynasty", "the 18th dynasty"],
    ["the II millennium BC", "the 2nd millennium BC"],
    ["XIX-century art", "19th-century art"],
    ["the XXII century", "the 22nd century"],
    ["the XIII century", "the 13th century"],
  ],
  "en list markers": [
    ["(i) apples, (ii) pears, (iii) plums", "(1) apples, (2) pears, (3) plums"],
    ["Remember (iv) and (v).", "Remember (4) and (5)."],
    ["clause 3(iii)", "clause 3(3)"],
    ["(a)(iv)", "(a)(4)"],
    ["(ii)(b)", "(2)(b)"],
    ["ii) the second point", "2) the second point"],
    ["iv. Mitochondria", "4. Mitochondria"],
    ["IV. Results", "4. Results"],
    ["Two reasons: (i) cost and (ii) time.", "Two reasons: (1) cost and (2) time."],
    ["I. Introduction", "1. Introduction"],
    ["Point (I) and point (II)", "Point (1) and point (2)"],
    ["Two steps: i) mix, ii) heat", "Two steps: 1) mix, 2) heat"],
    ["i) first ii) second", "1) first 2) second"],
    ["(iv) apples (v) pears", "(4) apples (5) pears"],
    ["IV. Results\nV. Conclusion", "4. Results\n5. Conclusion"],
    ["Figure 3(ii)", "Figure 3(2)"],
  ],
  "en more": [
    ["Chapter I explains cells.", "Chapter 1 explains cells."],
    ["Type I and type II errors", "Type 1 and type 2 errors"],
    ["World War II-era planes", "World War 2-era planes"],
    ["Grade II–III", "Grade 2–3"],
    ["Items I, II and III", "Items 1, 2 and 3"],
    ["the England XI", "the England 11"],
    ["Apollo XIII's crew", "Apollo 13's crew"],
    ["Henry VIII, Edward VI and Mary I", "Henry the Eighth, Edward the Sixth and Mary the First"],
    ["When I saw grade IV, I was shocked.", "When I saw grade 4, I was shocked."],
    ["Leo XIII wrote Rerum Novarum.", "Leo the Thirteenth wrote Rerum Novarum."],
    ["Type IV hypersensitivity is delayed.", "Type 4 hypersensitivity is delayed."],
    ["Factor X deficiency", "Factor 10 deficiency"],
    ["Volume V.", "Volume 5."],
    ["vol. V", "vol. 5"],
    ["the XVI Olympic Games", "the 16th Olympic Games"],
  ],
  "en more leave alone": same([
    "(x) is unknown",
    "x) = 2",
    "(v) velocity",
    "V. Conclusion",
    "X. Y. Z. are points",
    "Section 2.IV",
    "Rule 3.ii",
    "MCMLXXXIV by George Orwell",
    "Gen X and Gen Z",
    "Mark X",
    "unit V",
    "the X factor",
    "the XI of the team",
    "I, II and III are the options.",
    "the I-95 highway",
    "the V8 engine",
    "Is this the part I need?",
    "In the book I found a note.",
    "He spoke to David I believe.",
    "When I was young, Mark I think was right.",
    "the mark I got",
    "a section I wrote",
    "UNIT IV",
    "the Tudor dynasty",
  ]),
  "en oxidation states": [
    ["iron(III) oxide", "iron(3) oxide"],
    ["copper(II) sulfate", "copper(2) sulfate"],
    ["Fe(II) ions", "Fe(2) ions"],
    ["lead (II) nitrate", "lead (2) nitrate"],
  ],
  "en leave alone": same([
    "I think so.",
    "I LIVE HERE",
    "I MIX the colours",
    "She needs an IV drip.",
    "Start IV fluids now.",
    "IV fluids were given.",
    "Give IV antibiotics.",
    "Nurse Jones gave Morphine IV infusion.",
    "The patient had an MI.",
    "Take vitamin D daily.",
    "Vitamin C boosts immunity.",
    "He got a grade C.",
    "grade D",
    "Grade A work",
    "DC current flows one way.",
    "Washington DC",
    "Send me your CV.",
    "Burn a CD.",
    "She is an MD.",
    "Jane Smith MD",
    "the 95% CI was wide",
    "95% CI 1.2 to 3.4",
    "a size XL shirt",
    "Size XL",
    "an LCD screen",
    "Mix well.",
    "Li is lithium.",
    "the XX chromosomes",
    "Look at the X-ray.",
    "An X-ray showed a fracture.",
    "CIV was the answer.",
    "the part I like best",
    "The lesson I learned was simple.",
    "That is the type I prefer.",
    "the class I teach",
    "the book I read",
    "the chapter I wrote",
    "the scene I love",
    "the war I fought in",
    "the level I reached",
    "No. I disagree.",
    "No. I think not.",
    "Mary I think is right.",
    "I told Peter I would come.",
    "V = IR",
    "I = V/R",
    "Let x = 5.",
    "the velocity (v) of the car",
    "the current (I) in the wire",
    "f(x) = x^2",
    "the volume V of the gas",
    "a class X extends Y",
    "Generation X",
    "Tesla Model X",
    "Malcolm X",
    "Mac OS X",
    "The unit V is volts.",
    "See https://example.com/IV/page",
    "email MIX@example.com",
    "`MIX` is a macro",
    "use i.e. and e.g.",
    "the I/O port",
    "IV2 was the code",
    "I'm happy.",
    "I'd go.",
    "I've done it.",
    "XXL shirts",
    "a VIVID picture",
    "CIVIL rights",
    "Type 2 diabetes",
    "It's in Section C.",
    "Hepatitis C",
    "Model T",
    "the MIT study",
    "Grand Theft Auto V",
    "the Saturn V rocket",
    "Louis Vuitton LV bag",
    "the LV wall",
    "Data from the UK ML team",
    "He fought in WORLD WAR II",
    "PART II",
    "In MCMXCIX they built it",
    "the matrix M",
    "X marks the spot.",
    "vi is an editor",
    "mix it",
    "in 5 mm",
    "10 mL of water",
    "chapter C",
    "type C personality",
    "Class D amplifier",
    "the DIY store",
    "a MIDI keyboard",
    "the DVD player",
    "I will, I promise.",
    "Stage C",
    "an intravenous (IV) line",
    "myocardial infarction (MI)",
    "the Xi River",
    "MMR vaccine",
    "the CCD sensor",
    "ICU beds",
    "ill",
    "via IV route",
  ]),
  // ---------------------------------------------------------------- French
  fr: [
    ["François Ier", "François premier"],
    ["Napoléon Ier fut sacré en 1804.", "Napoléon premier fut sacré en 1804."],
    ["Louis XIV régna longtemps.", "Louis 14 régna longtemps."],
    ["Henri IV", "Henri 4"],
    ["Napoléon III", "Napoléon 3"],
    ["Élisabeth II", "Élisabeth 2"],
    ["Élisabeth I", "Élisabeth première"],
    ["François I", "François premier"],
    ["au XIXe siècle", "au 19e siècle"],
    ["le XVIIIᵉ siècle", "le 18e siècle"],
    ["le XXème siècle", "le 20ème siècle"],
    ["le Ier siècle", "le premier siècle"],
    ["la Ire République", "la première République"],
    ["la Ve République", "la 5e République"],
    ["le Xe siècle", "le 10e siècle"],
    ["la IIIe République", "la 3e République"],
    ["le XIX siècle", "le 19e siècle"],
    ["chapitre IV", "chapitre 4"],
    ["diabète de type II", "diabète de type 2"],
    ["le diabète de type I est fréquent", "le diabète de type 1 est fréquent"],
    ["stade III", "stade 3"],
    ["tome II", "tome 2"],
    ["article V", "article 5"],
    ["acte I, scène II", "acte 1, scène 2"],
    ["le concile Vatican II", "le concile Vatican 2"],
    ["classes I et II", "classes 1 et 2"],
    ["Apollo XIII", "Apollo 13"],
    ["(i) les pommes, (ii) les poires", "(1) les pommes, (2) les poires"],
    ["le pape Jean-Paul II", "le pape Jean-Paul 2"],
    ["les XVe et XVIe siècles", "les 15e et 16e siècles"],
    ["Il est né au IIIe siècle avant J.-C.", "Il est né au 3e siècle avant J.-C."],
    ["Louis XIV, dit le Roi-Soleil", "Louis 14, dit le Roi-Soleil"],
  ],
  "fr leave alone": same([
    "Il a un CV solide.",
    "la vitamine D",
    "le courant DC",
    "Xe est un gaz noble.",
    "Dix ans plus tard",
    "Je suis en CM2",
    "une taille XL",
    "le type X est inconnu",
  ]),
  // ---------------------------------------------------------------- Spanish
  es: [
    ["Felipe II", "Felipe segundo"],
    ["Carlos V fue emperador.", "Carlos quinto fue emperador."],
    ["Alfonso XIII", "Alfonso 13"],
    ["Isabel II", "Isabel segunda"],
    ["Isabel I de Castilla", "Isabel primera de Castilla"],
    ["Juan Carlos I", "Juan Carlos primero"],
    ["el papa Juan Pablo II", "el papa Juan Pablo segundo"],
    ["Benedicto XVI", "Benedicto 16"],
    ["Fernando VII", "Fernando séptimo"],
    ["el siglo XIX", "el siglo 19"],
    ["el siglo V", "el siglo quinto"],
    ["los siglos XV y XVI", "los siglos 15 y 16"],
    ["los siglos II y III", "los siglos segundo y tercero"],
    ["la II Guerra Mundial", "la segunda Guerra Mundial"],
    ["el I Congreso", "el primer Congreso"],
    ["capítulo IV", "capítulo 4"],
    ["diabetes tipo II", "diabetes tipo 2"],
    ["tipo I", "tipo 1"],
    ["fase III", "fase 3"],
    ["Felipe II y Felipe III", "Felipe segundo y Felipe tercero"],
    ["el siglo IV a. C.", "el siglo cuarto a. C."],
    ["Isabel I y Fernando II", "Isabel primera y Fernando segundo"],
  ],
  "es leave alone": same(["la vitamina D", "un CD nuevo", "Yo tengo un DVD", "una talla XL"]),
  // ---------------------------------------------------------------- Italian
  it: [
    ["Luigi XIV", "Luigi quattordicesimo"],
    ["Vittorio Emanuele II", "Vittorio Emanuele secondo"],
    ["Papa Giovanni Paolo II", "Papa Giovanni Paolo secondo"],
    ["Pio XII", "Pio dodicesimo"],
    ["Elisabetta II", "Elisabetta seconda"],
    ["Carlo V", "Carlo quinto"],
    ["Enrico VIII", "Enrico ottavo"],
    ["Papa Giovanni XXIII", "Papa Giovanni ventitreesimo"],
    ["il XIX secolo", "il diciannovesimo secolo"],
    ["il secolo XIX", "il secolo diciannovesimo"],
    ["la II guerra mondiale", "la seconda guerra mondiale"],
    ["la III dinastia", "la terza dinastia"],
    ["il XV e XVI secolo", "il quindicesimo e sedicesimo secolo"],
    ["capitolo IV", "capitolo 4"],
    ["diabete di tipo II", "diabete di tipo 2"],
    ["(i) mele, (ii) pere", "(1) mele, (2) pere"],
    ["Pio IX e Pio X", "Pio nono e Pio decimo"],
    ["la I guerra mondiale", "la prima guerra mondiale"],
    ["nel XIV secolo", "nel quattordicesimo secolo"],
  ],
  "it leave alone": same(["i libri sono qui", "vi prego", "la vitamina C", "il CD"]),
  // ---------------------------------------------------------------- Portuguese
  pt: [
    ["Pedro I", "Pedro primeiro"],
    ["Dom Pedro II", "Dom Pedro segundo"],
    ["Maria I", "Maria primeira"],
    ["João VI", "João sexto"],
    ["Luís XIV", "Luís 14"],
    ["o século XIX", "o século 19"],
    ["o século V", "o século quinto"],
    ["a II Guerra Mundial", "a segunda Guerra Mundial"],
    ["capítulo III", "capítulo 3"],
    ["diabetes tipo II", "diabetes tipo 2"],
    ["papa João Paulo II", "papa João Paulo segundo"],
    ["D. João VI", "D. João sexto"],
    ["no século XV", "no século 15"],
  ],
  "pt leave alone": same(["a vitamina D", "um CD", "tamanho XL"]),
  // ---------------------------------------------------------------- German
  de: [
    ["Ludwig XIV. war König.", "Ludwig der Vierzehnte war König."],
    ["unter Ludwig XIV. blühte", "unter Ludwig dem Vierzehnten blühte"],
    ["die Herrschaft Ludwigs XIV.", "die Herrschaft Ludwigs des Vierzehnten."],
    ["für Karl V.", "für Karl den Fünften."],
    ["Friedrich II. von Preußen", "Friedrich der Zweite von Preußen"],
    ["Königin Elisabeth II. starb 2022.", "Königin Elisabeth die Zweite starb 2022."],
    ["mit Königin Elisabeth II.", "mit Königin Elisabeth der Zweiten."],
    ["Kaiser Wilhelm II. dankte ab.", "Kaiser Wilhelm der Zweite dankte ab."],
    ["Papst Johannes Paul II.", "Papst Johannes Paul der Zweite."],
    ["im XIX. Jahrhundert", "im 19. Jahrhundert"],
    ["das XX Jahrhundert", "das 20. Jahrhundert"],
    ["Kapitel IV", "Kapitel 4"],
    ["Typ-II-Diabetes", "Typ-2-Diabetes"],
    ["Typ I", "Typ 1"],
    ["Teil III", "Teil 3"],
    ["Band II", "Band 2"],
    ["Stadium IV", "Stadium 4"],
    ["Klassen I und II", "Klassen 1 und 2"],
    ["der II. Weltkrieg", "der 2. Weltkrieg"],
    ["Heinrich IV. ging nach Canossa.", "Heinrich der Vierte ging nach Canossa."],
    ["das III. Reich", "das 3. Reich"],
    ["von Otto I.", "von Otto dem Ersten."],
    ["der Typ-I-Diabetes", "der Typ-1-Diabetes"],
  ],
  "de leave alone": same(["Vitamin D", "die DC-Spannung", "ein CD-Spieler", "Größe XL"]),
};

for (const [group, list] of Object.entries(cases)) {
  const lang = group.split(" ")[0];
  for (const [input, spoken] of list) {
    test(`${group}: ${input}`, () => {
      assert.equal(forSpeech(input, lang), spoken);
    });
  }
}

// ---------------------------------------------------------------- language tags
const tagged: Array<[string, string | undefined, string]> = [
  ["grade IV", "en-GB", "grade 4"],
  ["grade IV", "en-US", "grade 4"],
  ["grade IV", undefined, "grade 4"],
  ["grade IV", "", "grade 4"],
  ["Louis XIV", "fr-FR", "Louis 14"],
  ["Louis XIV", "FR", "Louis 14"],
  ["Louis XIV", "fr_CA", "Louis 14"],
  ["Pedro II", "pt-BR", "Pedro segundo"],
  ["Felipe II", "es-MX", "Felipe segundo"],
  ["Luigi XIV", "it-IT", "Luigi quattordicesimo"],
  ["Kapitel IV", "de-AT", "Kapitel 4"],
  // Languages without rules are left alone, never read with English rules.
  ["Henry VIII", "ar", "Henry VIII"],
  ["الفصل IV", "ar-SA", "الفصل IV"],
  ["grade IV", "ja", "grade IV"],
  ["hoofdstuk IV", "nl", "hoofdstuk IV"],
  ["Louis XIV", "zh", "Louis XIV"],
];
for (const [input, lang, spoken] of tagged) {
  test(`lang ${String(lang)}: ${input}`, () => assert.equal(forSpeech(input, lang), spoken));
}

test("English regnal words never reach other languages", () => {
  for (const lang of ["fr", "es", "it", "pt", "de"]) {
    assert.doesNotMatch(forSpeech("Louis XIV et Henri IV", lang), /the /);
  }
});

test("captions untouched: text without numerals comes back identical", () => {
  const s = "Photosynthesis turns light into chemical energy — no numerals here!";
  assert.equal(forSpeech(s), s);
  assert.equal(forSpeech(""), "");
});

// ---------------------------------------------------------------- properties
const allInputs = [...Object.entries(cases).flatMap(([g, l]) => l.map(([s]) => [s, g.split(" ")[0]] as const))];

test("idempotent on every case", () => {
  for (const [input, lang] of allInputs) {
    const once = forSpeech(input, lang);
    assert.equal(forSpeech(once, lang), once, `${lang}: ${input}`);
  }
});

// A small seeded generator, so a failure is reproducible.
function rng(seed: number) {
  return () => {
    seed = (seed * 1103515245 + 12345) & 0x7fffffff;
    return seed / 0x7fffffff;
  };
}
const PIECES = [
  "I", "V", "X", "L", "C", "D", "M", "IV", "XIX", "iii", "(", ")", ".", ",", " ", " ", " ", "-", "/", "'s", "e", "er",
  "grade", "Type", "Henry", "Louis", "World", "War", "siècle", "siglo", "secolo", "Jahrhundert", "No.", "and", "und",
  "=", "`", "http://", "2", "é", "\n", ":", "Apollo", "century", "the", "Ludwig", "unter", "ᵉ", "º", "°",
];

test("never throws and stays idempotent on random text", () => {
  const rand = rng(42);
  for (let n = 0; n < 3000; n++) {
    let s = "";
    const len = 1 + Math.floor(rand() * 14);
    for (let k = 0; k < len; k++) s += PIECES[Math.floor(rand() * PIECES.length)];
    const lang = ["en", "fr", "es", "it", "pt", "de", "ar"][n % 7];
    const once = forSpeech(s, lang);
    assert.equal(typeof once, "string");
    assert.equal(forSpeech(once, lang), once, `${lang}: ${JSON.stringify(s)}`);
  }
});

test("never throws on bad input", () => {
  for (const bad of [null, undefined, 42, {}, []]) {
    assert.doesNotThrow(() => forSpeech(bad as unknown as string));
    assert.equal(typeof forSpeech(bad as unknown as string), "string");
  }
});

test("fast enough to run on every sentence", () => {
  const sentence =
    "In the XIX century, after World War I and Types I and II, Henry VIII and Louis XIV read Chapter IV (ii) of Volume III while I think about grade IV and an IV drip.";
  const start = Date.now();
  for (let n = 0; n < 2000; n++) forSpeech(sentence, "en");
  assert.ok(Date.now() - start < 1500, `2000 sentences took ${Date.now() - start} ms`);
});
